# Generated by Django 4.2.20 on 2025-05-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
